title: Kocin Sabareeswaran Bama # your name (or website title) here
logo: "/images/ppn.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  I am a Strongly motivated student, openminded to see any potential aproaching opertunity and determinded to give my best at any work I am involved.
  Creative mind helps me break boundaries set in jobs and think outside the box. 
  <br><br>
   <a href="https://www.linkedin.com/in/kocin-sb/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
